name: Quick B200 Test

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
    tags:
      - ciflow/pull/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  quick-test:
    runs-on: [self-hosted, B200]
    steps:
      - name: Quick GPU test
        run: |
          whoami
          nvidia-smi
          nvidia-smi --query-gpu=compute_cap --format=csv
          sleep 3600
  quick-test2:
    runs-on: [self-hosted, linux.dgx.b200.8]
    steps:
      - name: Quick GPU test
        run: |
          whoami
          nvidia-smi
          nvidia-smi --query-gpu=compute_cap --format=csv
          sleep 3600
  quick-test3:
    runs-on: [self-hosted, linux.dgx.b200.8]
    steps:
      - name: Quick GPU test
        run: |
          whoami
          nvidia-smi
          nvidia-smi --query-gpu=compute_cap --format=csv
